config/routes.rb
Rails.application.routes.draw do
  resources :pomodoroapps
  resources :categories

  root 'pomodoroapps#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/pomodoroapp.rb
class Pomodoroapp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new 
    @categories = categories.all
  end

  def show 
    @category = Category.find(params[:id])
  end  

  def edit
    @category = category.find(params[:id])
  end
 
  def create
    @category = Category.new(category_params)
 
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end
  
  def update
    @category = Category.find(params[:id])
   
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end
 
 private
  def category_params
    params.require(:category).permit(:title, :text)
  end
    
end

app/controllers/pomodoroapps_controller.rb
class PomodoroappsController < ApplicationController
  before_action :set_pomodoroapp, only: [:show, :edit, :update, :destroy]

  # GET /pomodoroapps
  # GET /pomodoroapps.json
  def index
    @pomodoroapps = Pomodoroapp.all
  end

  # GET /pomodoroapps/1
  # GET /pomodoroapps/1.json
  def show
  end

  # GET /pomodoroapps/new
  def new
    @pomodoroapp = Pomodoroapp.new
  end

  # GET /pomodoroapps/1/edit
  def edit
  end

  # POST /pomodoroapps
  # POST /pomodoroapps.json
  def create
    @pomodoroapp = Pomodoroapp.new(pomodoroapp_params)

    respond_to do |format|
      if @pomodoroapp.save
        format.html { redirect_to @pomodoroapp, notice: 'Pomodoroapp was successfully created.' }
        format.json { render :show, status: :created, location: @pomodoroapp }
      else
        format.html { render :new }
        format.json { render json: @pomodoroapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pomodoroapps/1
  # PATCH/PUT /pomodoroapps/1.json
  def update
    respond_to do |format|
      if @pomodoroapp.update(pomodoroapp_params)
        format.html { redirect_to @pomodoroapp, notice: 'Pomodoroapp was successfully updated.' }
        format.json { render :show, status: :ok, location: @pomodoroapp }
      else
        format.html { render :edit }
        format.json { render json: @pomodoroapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pomodoroapps/1
  # DELETE /pomodoroapps/1.json
  def destroy
    @pomodoroapp.destroy
    respond_to do |format|
      format.html { redirect_to pomodoroapps_url, notice: 'Pomodoroapp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pomodoroapp
      @pomodoroapp = Pomodoroapp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pomodoroapp_params
      params.require(:pomodoroapp).permit(:name, :client, :date, :projectname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pomodoroapps_helper.rb
module PomodoroappsHelper
end

app/views/categories/index.html.erb
<h2>Heowdy</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomodoro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <link rel="stylesheets" href="stylesheets/application.css"> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pomodoroapps/_form.html.erb
<%= form_for(@pomodoroapp) do |f| %>
  <% if @pomodoroapp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pomodoroapp.errors.count, "error") %> prohibited this pomodoroapp from being saved:</h2>

      <ul>
      <% @pomodoroapp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :projectname %><br>
    <%= f.text_field :projectname %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pomodoroapps/edit.html.erb
<h1>Editing Pomodoroapp</h1>

<%= render 'form' %>

<%= link_to 'Show', @pomodoroapp %> |
<%= link_to 'Back', pomodoroapps_path %>

app/views/pomodoroapps/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <!-- <link rel="stylesheet" href="application.css"> -->
    <link rel="stylesheets" href="stylesheets/application.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>

  <!-- <p id="notice"><%= notice %></p> -->

  <body>
    

      <div class="inspiration">
        <div id="clock"></div>
        <div class="introtag">
          <h2> Howdy, Matt</h2>
        </div>
        <br>
        <div class="gap_filler"></div>
        <div class="quote">
          <strong><div id='quoteAJAX'></div></strong>
          <div id="response"></div>
          <div id="response1"></div>
          <div id="log"></div>
        </div>
      </div>
  


<!-- Add a Pomodoro coutdown section -->
<!-- This became a countdown for a new adventure and city -->

      <div class="pomodoro_countdown">
      <p class="hide_adventure_countdown">x</p>
        <div class="clockdiv_and_h1">
          <h1>New challenge and New city</h1>
          <br />
          
          <div id="clockdiv">
            <div>
              <span class="days"></span>
              <div class="smalltext">Days</div>
            </div>
            <div>
              <span class="hours"></span>
              <div class="smalltext">Hours</div>
            </div>
            <div>
              <span class="minutes"></span>
              <div class="smalltext">Minutes</div>
            </div>
            <div>
              <span class="seconds"></span>
              <div class="smalltext">Seconds</div>
            </div>
          </div>
        </div>
       
        <br>
        <br>

          <div class="buttons">
              <button id="buttonstart" onclick="startClock()">Start</button>
          </div>
        <br>
        <br>
      </div> 



<!-- Pomodoro minute countdown area  -->

     <!-- <div class="pomodoro_builder"> -->
      <div class="outerClock">
        <h1>Pomodoro Countdown</h1>
        <button id="adventure_comeback">x</button>
        <div class="pomodoro_circle">
          
          <div id="timeDiv">
            <!-- <h1>Pomodoro Countdown</h1> -->
            <br />
            <h3 class="title_2">Session Time</h3>


            <!-- By removeing the href="#" we were able to stop the pomodor clock jumping up and not working -->


            <!-- <a href="#" class="btn btn-default" id="minus5clock">-</a>  -->
            <a class="btn btn-default" id="minus5clock">-</a> 

            <!-- <h2 id="timeType"></h2> -->
            <h2 id="num">5</h2>
            <!-- <a href="" class="btn btn-default" id="add5clock">+</a>  -->
            <a class="btn btn-default" id="add5clock">+</a> 
<!--             <a href="#" class="btn btn-danger" id="reset">Reset</a> 
 -->        <a class="btn btn-danger" id="reset">Reset</a> 

          </div>

          <div id="breakDiv">
          <h3 class="title_2">Break Time</h3>
            <a class="btn btn-default" id="minus5break">-</a> 
            <h2 id="breakNum">5</h2>
            <a class="btn btn-default" id="add5break">+</a> 
          </div>
            <br />
            <a class="btn btn-default" id="start">Start</a>
        </div>  
      </div>
    <!-- </div>  -->






<!-- Add a section to record the total work done by category  -->

      

      <div class="records-of-sessions">
        <h1>Total Work Done by Category</h1>
        <div class= "sessions">
          <div class="liveandwork"></div>
          <div class="travelersandlocals"></div>
          <div class="cinegears"></div>
        </div>
        <div class="sessions2">
          <div class="wordpress"></div>
          <div class="marketing"></div>
          <div class="writing"></div>
        </div>  
        </div>
      </div>  
    <!-- </div> -->





<!-- Add a section to record the new work session -->

<div class="worksessions">
  <table class="latestworksessions">
  <h2>Latest Work Sessions</h2>
  <br>
    <thead>
      <tr>
        <th>Projectname</th>
        <!-- <th class="fffff">Name</th>
 -->        <th>Client</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pomodoroapps.each do |pomodoroapp| %>
        <tr>
          <td class="projectname"><%= pomodoroapp.projectname %></td>
          <!-- <td class="fffff"><%= pomodoroapp.name %></td> -->
          <td><%= pomodoroapp.client %></td>
          <!-- <td><%= pomodoroapp.date %></td> -->
          <td><%= pomodoroapp.time %></td> 
          <td class="show"><%= link_to 'Show', pomodoroapp %></td>
          <td class="btn btn-primary"><%= link_to 'Edit', edit_pomodoroapp_path(pomodoroapp) %></td>
          <td class="btn btn-danger"><%= link_to 'Destroy', pomodoroapp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

    <button class="btn btn-default" class="add_session"><%= link_to 'Add Session', new_pomodoroapp_path %></button>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>
</html>

<!-- 
//At the end of a pomodoro cycle 

//add the option to click the add session button 

//Add that to your Total work by category. -->

app/views/pomodoroapps/new.html.erb
<h1>New Session</h1>

<%= render 'form' %>

<%= link_to 'Back', pomodoroapps_path %>

app/views/pomodoroapps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pomodoroapp.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @pomodoroapp.client %>
</p>

<p>
  <strong>Date:</strong>
  <%= @pomodoroapp.date %>
</p>

<p>
  <strong>Projectname:</strong>
  <%= @pomodoroapp.projectname %>
</p>

<p>
  <strong>Time:</strong>
  <%= @pomodoroapp.time %>
</p>

<%= link_to 'Edit', edit_pomodoroapp_path(@pomodoroapp) %> |
<%= link_to 'Back', pomodoroapps_path %>